name       : cubeb
version    : 20230731
release    : 1
source     :
    - git|https://github.com/mozilla/cubeb : b9af56cee792f17a466db7b3ac3382262782c6f1
license    : ISC
component  : multimedia.audio
summary    : A cross-platform audio library
description: |
    A cross-platform audio library developed by Mozilla.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(jack)
    - pkgconfig(libpulse)
    - pkgconfig(sndio)
    - pkgconfig(speexdsp)
    - gtest-devel
setup      : |
    # https://github.com/mozilla/cubeb/issues/736
    sed -i '/cubeb_add_test(logging)/d' CMakeLists.txt
    %cmake -B build \
        -DBUILD_SHARED_LIBS=ON \
        -DBUNDLE_SPEEX=OFF \
        -DCMAKE_BUILD_TYPE=Release \
        -DUSE_SANITIZERS=OFF
build      : |
    cmake --build build
install    : |
    DESTDIR=$installdir cmake --install build
check      : |
    ctest --test-dir build -E 'audio|callback_ret|device_changed_callback|devices|duplex|latency|record|sanity|tone'